import 'dart:io';
import 'package:dio/dio.dart';
import 'package:firstapp1/model/currency_model.dart';
import 'package:hive/hive.dart';
import 'package:path_provider/path_provider.dart';

class GetService {
  static Box<Autogenerated>? currencyBox;
  static Future<dynamic> getUser() async {
    await openBox();
    try {
      Response res = await Dio().get("https://nbu.uz/uz/exchange-rates/json/");
      if (res.statusCode == 200) {
        List<Autogenerated> resData =
            (res.data as List).map((e) => Autogenerated.fromJson(e)).toList();
        await putToBox(resData);
        return res.data;
      } else {
        return res.statusMessage;
      }
    } catch (e) {
      throw e.toString();
    }
  }

  static openBox() async {
    Directory appDocDir = await getApplicationDocumentsDirectory();
    Hive.init(appDocDir.path);
    currencyBox = await Hive.openBox<Autogenerated>("currency");
  }

  static putToBox(List<Autogenerated> data) async {
    for (Autogenerated element in data) {
      await currencyBox!.add(element);
    }
    print("Successful");
  }

  static void registerAdapters() async {
    Hive.registerAdapter(AutogeneratedAdapter());
  }
}
